//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFertilizerWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Comments = new HashSet<Comment>();
            this.Transactions = new HashSet<Transaction>();
        }

        [Required] // Không được bỏ trống
        // Dùng biểu thức kiểm tra đúng yêu cầu không
        [RegularExpression(@"^[a-z][a-z0-9_]{2,32}@[a-z0-9]{2,}([.][a-z0-9]{2,4}){1,2}$", ErrorMessage ="Email không hợp lệ")] 
    
        public string Email { get; set; }
        [Required]
        [StringLength(50, MinimumLength =3, ErrorMessage ="Tên phải từ 3 đến 50 kí tự")]
        public string Name { get; set; }
        [Required]
        [StringLength(50, MinimumLength =1,ErrorMessage ="Mật khẩu phải từ 1 đến 50 kí tự")]
        public string Password { get; set; }
        [NotMapped]
        [Required]
        [Compare("Password", ErrorMessage ="Mật khẩu nhập lại không giống!")]
        public string RePassword { get; set; }
        public int RoleID { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
