//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFertilizerWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        public int ID { get; set; }
        public string CustomerEmail { get; set; }
        [Required]
        public int ProductID { get; set; }
        [Required]
        [StringLength(200, MinimumLength =3, ErrorMessage ="Comment phải từ 3 đến 200 kí tự!")]
        [DataType(DataType.MultilineText)]
        public string Message { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Product Product { get; set; }
    }
}
